apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-app
  template:
    metadata:
      labels:
        app: broken-app
    spec:
      containers:
      - name: broken-app
        image: cachac/non-existent-image:99.0
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 80m
            memory: 128Mi
